"""empty message

Revision ID: 155d42eb5c3
Revises: 2785ff12b87
Create Date: 2016-08-21 12:53:42.037497

"""

# revision identifiers, used by Alembic.
revision = '155d42eb5c3'
down_revision = '2785ff12b87'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guidebook', sa.Column('added', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guidebook', 'added')
    ### end Alembic commands ###
