"""empty message

Revision ID: 1a91cac51979
Revises: 155d42eb5c3
Create Date: 2017-03-05 19:09:34.280345

"""

# revision identifiers, used by Alembic.
revision = '1a91cac51979'
down_revision = '155d42eb5c3'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('_tags_string', sa.Text(), nullable=True))
    op.drop_column('guidebook', 'added')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guidebook', sa.Column('added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('calendar_event', '_tags_string')
    # ### end Alembic commands ###
