"""empty message

Revision ID: 211a51e31795
Revises: 1a91cac51979
Create Date: 2018-03-18 19:28:33.926203

"""

# revision identifiers, used by Alembic.
revision = '211a51e31795'
down_revision = '1a91cac51979'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_image', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post_image', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_image', type_='foreignkey')
    op.drop_column('post_image', 'author_id')
    # ### end Alembic commands ###
