"""empty message

Revision ID: 23e3546d64e
Revises: 581030ed87b
Create Date: 2016-04-28 23:28:28.776323

"""

# revision identifiers, used by Alembic.
revision = '23e3546d64e'
down_revision = '581030ed87b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('end', sa.DateTime(), nullable=True))
    op.add_column('calendar_event', sa.Column('start', sa.DateTime(), nullable=True))
    op.add_column('calendar_event', sa.Column('title', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event', 'title')
    op.drop_column('calendar_event', 'start')
    op.drop_column('calendar_event', 'end')
    ### end Alembic commands ###
