"""empty message

Revision ID: 7bbcecd68b24
Revises: 932eae38164b
Create Date: 2018-04-27 21:13:17.552667

"""

# revision identifiers, used by Alembic.
revision = '7bbcecd68b24'
down_revision = '932eae38164b'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('short_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'short_html')
    # ### end Alembic commands ###
