"""empty message

Revision ID: 932eae38164b
Revises: 211a51e31795
Create Date: 2018-03-21 12:22:13.875784

"""

# revision identifiers, used by Alembic.
revision = '932eae38164b'
down_revision = '211a51e31795'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_image_author_id_fkey', 'post_image', type_='foreignkey')
    op.drop_column('post_image', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_image', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('post_image_author_id_fkey', 'post_image', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
