"""empty message

Revision ID: b1f665d4b0
Revises: 3c58d893af4
Create Date: 2015-09-27 12:35:01.319772

"""

# revision identifiers, used by Alembic.
revision = 'b1f665d4b0'
down_revision = '3c58d893af4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
